### ISSUE TITLE
Error modules. Solution

### ISSUE THREAD

**Issue by wljtcc** [dsestero/download_uncompress#1]
site.pp config:
download_uncompress {'Test_tar_gz':
        #download_base_url  => 'http://url_base',
        distribution_name => 'http://url_base/putty.tar.gz',
        dest_folder   => '/opt',
        creates       => '/opt/putty',
        uncompress    => 'tar.gz',
}

Module Error:
[root@infragccli opt]# puppet agent --test 
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for infragccli.dataeasy.com.br
Error: Failed to apply catalog: Validation of Exec[download_uncompress_http://download.domain.com.br/instalacao/putty.tar.gz-/opt] failed: 'wget http://download.domain.com.br/instalacao/putty.tar.gz -O /tmp/putty.tar.gz && mkdir -p /opt/putty && tar xzf /tmp/putty.tar.gz -C /opt/putty' is not qualified and no path was specified. Please qualify the command or specify a path. at /etc/puppet/modules/download_uncompress/manifests/init.pp:89

Modify module ( /etc/puppet/modules/download_uncompress/manifests/init.pp ):
$cmd = $uncompress ? {
  'zip'    => "wget ${download_url} -O /tmp/${file_name} && mkdir -p ${creates} && unzip /tmp/${file_name} -d ${creates}",
  'tar.gz' => "wget ${download_url} -O /tmp/${file_name} && mkdir -p ${creates} && tar xzf /tmp/${file_name} -C ${creates}",
  default  => "wget -P ${dest_folder} ${download_url}",
  }

  exec { "download_uncompress_${download_url}-${dest_folder}":
    command   => $cmd,
    creates   => $creates,
    user      => $user,
    group     => $group,
    path      => "/usr/local/bin/:/bin/",
    logoutput => 'on_failure',
    require   => Class['Download_uncompress::Dependencies'],
  }

**Comment by dsestero** [comment]
Hi wljtcc and thanks for your comment. 

Yes, the search path used for command execution has to be specified somewhere. Usually it is set in the `site.pp` for your execution environment. For example, there I have:

```
Exec {
  path  => [
    '/usr/local/bin',
    '/opt/local/bin',
    '/usr/bin',
    '/usr/sbin',
    '/bin',
    '/sbin',
  ],
  logoutput => true,
}
```

Alternatively it could be passed as `path` parameter or the commands must be fully qualified.

I will do it in the next version or put a notice on the requirement chapter of the README.markdown

Best regards,
Dario Sestero

**Comment by dsestero** [comment]
Hi,
in the 1.2.0 version just released the path is explicitly passed to the exec resource. 

Enjoy!
Dario
